
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security-demo?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  redis:
    url: 127.0.0.1
    port: 6379
  session:
    store-type: none
#  security:
#    user:
#      password: 123456
#      roles: [ADMIN,USER]

server:
  port: 8080
com:
  hejz:
    browser:
      loginPage: /demo-signIn.html
#      loginType: REDIRECT